controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_bazu_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_bazu_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_4
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

